name: payjp_checkout_example
description: "PAY.JP Checkout V2 sample (Flutter)."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  url_launcher: ^6.3.1
  app_links: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
